version: '3'

services:

  flask:
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: flask
    ports:
      - '5000:5000'
